---
name: New Releases

on:
  workflow_dispatch:
  
permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:

  build_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    env:
      repo: ${{ github.repository }}
    steps:
      - id: create-matrix
        name: Create matrix
        uses: dustindortch/github-actions-release-flow@1
        with:
          app-id: ${{ vars.FILTER_APP_ID }}
          private-key: ${{ secrets.FILTER_APP_PRIVATE_KEY }}
          filter-on: 'RELEASE'
          filter-by: 'releases/1.0'

  run_workflow:
    needs: build_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.build_matrix.outputs.matrix) }}
    environment: ${{ matrix.environment }}
    steps:
      - id: run-workflow
        name: Run workflow
        run: |
          set -eux
          echo "Running workflow for ${{ matrix.environment }}"

...
