---
name: New Releases

on:
  push:
    branches:
      - releases/**
  
permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:

  release_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    env:
      repo: ${{ github.repository }}
    steps:
      - id: create-matrix
        name: Create matrix
        uses: dustindortch/github-actions-release-flow@v1
        with:
          app-id: ${{ vars.FILTER_APP_ID }}
          private-key: ${{ secrets.FILTER_APP_PRIVATE_KEY }}
          filter-by: ${{ github.ref_name }}

  run_workflow:
    needs: release_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ needs.release_matrix.outputs.matrix }}
    environment: ${{ matrix.environment }}
    steps:
      - id: run-workflow
        name: Run workflow
        run: |
          set -eux
          echo "Running workflow for ${{ matrix.environment }}"

...